FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build   
WORKDIR /auth-api
   
# copy source
COPY . .

RUN dotnet restore  
RUN dotnet build --configuration Release 
RUN dotnet publish -c Release -o out   

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime   
WORKDIR /auth-api   
COPY --from=build /auth-api/out ./

# Padrão de container ASP.NET
# ENTRYPOINT ["dotnet", "crud.api.dll"]
# Opção utilizada pelo Heroku
# CMD ASPNETCORE_URLS=http://*:$PORT dotnet crud.api.dll

CMD ASPNETCORE_URLS=http://*:$PORT dotnet acount.api.dll